name: sleek_storage_benchmark
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Competitors
  sleek_storage:
    path: ../sleek_storage
  shared_preferences: ^2.5.3
  hive_ce: ^2.13.2
  drift_flutter: ^0.2.7

  # Tools
  path: ^1.9.1
  path_provider: ^2.1.5
  csv: ^6.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
