name: sleek_storage
description: Simple, reactive and lightweight key-value store that saves data in a JSON file
version: 2.0.0
repository: https://github.com/IcySunStudio/sleek_storage
issue_tracker: https://github.com/IcySunStudio/sleek_storage/issues

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.9.1
  value_stream: ^1.1.0

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
