name: sleek_storage_flutter
description: Flutter version of sleek_storage
version: 1.0.0
repository: https://github.com/IcySunStudio/sleek_storage
issue_tracker: https://github.com/IcySunStudio/sleek_storage/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sleek_storage: #^1.0.0
    path: ../sleek_storage

dev_dependencies:
  flutter_lints: ^6.0.0
